### ISSUE TITLE
[BUG] CUDA graph capture failed.

### ISSUE THREAD

**Issue by Alan-Heoooh** [rewarped/rewarped#22]
### Bug Description

Thank you for releasing this wonderful work. However, I encountered some problem when executing the script you provided. 

The error message is 
```
Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)
Warp CUDA error: Loading module failed
Module rewarped.warp.collide 4936e06 load on device 'cuda:0' took 0.50 ms  (error)
Traceback (most recent call last):
  File "/home/yulin/Documents/zihao/rewarped/rewarped/autograd.py", line 94, in forward
    sim_update(update_params, sim_params, states_bwd, control_bwd)
  File "/home/yulin/Documents/zihao/rewarped/rewarped/warp_utils.py", line 43, in sim_update
    wp.sim.collide(model, state_0)
  File "/home/yulin/Documents/zihao/rewarped/rewarped/warp/collide.py", line 1457, in collide
    wp.launch(
  File "/home/yulin/software/miniconda3/envs/rewarped/lib/python3.10/site-packages/warp/context.py", line 4726, in launch
    module_exec = kernel.module.load(device)
  File "/home/yulin/software/miniconda3/envs/rewarped/lib/python3.10/site-packages/warp/context.py", line 1928, in load
    raise Exception(f"Failed to load CUDA module '{self.name}'")
Exception: Failed to load CUDA module 'rewarped.warp.collide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yulin/software/miniconda3/envs/rewarped/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yulin/software/miniconda3/envs/rewarped/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yulin/Documents/zihao/rewarped/rewarped/envs/warp_examples/bounce.py", line 228, in <module>
    run_env(Bounce, no_grad=False)
  File "/home/yulin/Documents/zihao/rewarped/rewarped/environment.py", line 748, in run_env
    steps_per_second = demo.run()
  File "/home/yulin/Documents/zihao/rewarped/rewarped/warp_env.py", line 632, in run
    traj = self.run_episode(init_obs, policy)
  File "/home/yulin/Documents/zihao/rewarped/rewarped/warp_env.py", line 671, in run_episode
    obs, reward, done, info = self.step(action)
  File "/home/yulin/Documents/zihao/rewarped/rewarped/warp_env.py", line 458, in step
    self.do_physics_step()
  File "/home/yulin/Documents/zihao/rewarped/rewarped/warp_env.py", line 414, in do_physics_step
    outputs = UpdateFunction.apply(
  File "/home/yulin/software/miniconda3/envs/rewarped/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/yulin/Documents/zihao/rewarped/rewarped/autograd.py", line 96, in forward
    integrator.update_graph = wp.capture_end()
  File "/home/yulin/software/miniconda3/envs/rewarped/lib/python3.10/site-packages/warp/context.py", line 5107, in capture_end
    raise RuntimeError(f"CUDA graph capture failed. {runtime.get_error_string()}")
RuntimeError: CUDA graph capture failed. Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)

```

### System Information

I tried the commands on the following environment: RTX 4090, Ubuntu 22.04, CUDA 12.2, Python 3.10, PyTorch 2.3.1.

**Comment by Alan-Heoooh** [comment]
The only difference between my environment and author's is the CUDA version. Is it possible that this problem relates to the version?

**Comment by etaoxing** [comment]
Sorry about the delayed response, have been traveling.

What version of Warp are you on? You can also try PyTorch 2.6.0 and CUDA 12.5 to match my environment setup, although I'm not sure why that would be causing issues. Did you [install CUDA using a runfile](https://docs.omniverse.nvidia.com/dev-guide/latest/linux-troubleshooting.html#q1-how-to-install-a-driver) or apt-get?

Attaching a log of the expected output for reference. [bounce.txt](https://github.com/user-attachments/files/20094669/bounce.txt)

**Comment by Alan-Heoooh** [comment]
Thank you for your response. Already solved the issue by upgrade CUDA version to 12.8.
