### ISSUE TITLE
[BUG] Exception: CUDA graph capture failed. Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module,

### ISSUE THREAD

**Issue by fengjungui** [rewarped/rewarped#24]
### Bug Description

When I run this cmd "python -m rewarped.envs.warp_examples.bounce --num_envs 4",I get this erro

Exception: CUDA graph capture failed. Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)

**Comment by fengjungui** [comment]
Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)
Warp CUDA error: Loading module failed
Module rewarped.warp.collide 4936e06 load on device 'cuda:0' took 0.22 ms  (error)
Traceback (most recent call last):
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/autograd.py", line 94, in forward
    sim_update(update_params, sim_params, states_bwd, control_bwd)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/warp_utils.py", line 43, in sim_update
    wp.sim.collide(model, state_0)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/warp/collide.py", line 1457, in collide
    wp.launch(
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/warp/context.py", line 4726, in launch
    module_exec = kernel.module.load(device)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/warp/context.py", line 1928, in load
    raise Exception(f"Failed to load CUDA module '{self.name}'")
Exception: Failed to load CUDA module 'rewarped.warp.collide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/envs/warp_examples/bounce.py", line 228, in <module>
    run_env(Bounce, no_grad=False)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/environment.py", line 748, in run_env
    steps_per_second = demo.run()
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/warp_env.py", line 632, in run
    traj = self.run_episode(init_obs, policy)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/warp_env.py", line 671, in run_episode
    obs, reward, done, info = self.step(action)
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/warp_env.py", line 458, in step
    self.do_physics_step()
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/warp_env.py", line 414, in do_physics_step
    outputs = UpdateFunction.apply(
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/rewarped/autograd.py", line 96, in forward
    integrator.update_graph = wp.capture_end()
  File "/home/roboter/miniconda3/envs/sapo/lib/python3.10/site-packages/warp/context.py", line 5107, in capture_end
    raise RuntimeError(f"CUDA graph capture failed. {runtime.get_error_string()}")
RuntimeError: CUDA graph capture failed. Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)

**Comment by Alan-Heoooh** [comment]
Hi, I also encountered this problem before (#22). What's your system information (CUDA version)? I solved it by upgrading CUDA version.

**Comment by etaoxing** [comment]
Please use the minimum CUDA version required by Warp: "Warp packages built with CUDA Toolkit 12.x require NVIDIA driver 525 or newer."

**Comment by fengjungui** [comment]
OK,thanks


---Original---
From: ***@***.***&gt;
Date: Sat, May 10, 2025 05:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rewarped/rewarped] [BUG] Exception: CUDA graph capture failed.Warp CUDA error 900: operation not permitted when stream is capturing (infunction cuda_load_module, (Issue #24)


 etaoxing left a comment (rewarped/rewarped#24)
 
Please use the minimum CUDA version required by Warp: "Warp packages built with CUDA Toolkit 12.x require NVIDIA driver 525 or newer."
 
&mdash;

**Comment by fengjungui** [comment]
@etaoxing "Hi @etaoxing, I've updated to the latest environment (v1.2.3), but the [specific issue description] persists. Attached are the error logs and environment details. Could you advise on further diagnostics?"

 NVIDIA-SMI 535.216.03             Driver Version: 535.216.03   CUDA Version: 12.2
CUDA is available
CUDA version: 12.6
PyTorch version: 2.7.0+cu126
Current device: 0
Current device name: NVIDIA GeForce RTX 4090
Number of GPUs: 4
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 4090
GPU 3: NVIDIA GeForce RTX 4090
Warp 1.3.3 initialized:
   CUDA Toolkit 12.5, Driver 12.2
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
     "cuda:1"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
     "cuda:2"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
     "cuda:3"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   CUDA peer access:
     Not supported
   Kernel cache:
     /home/haichao/.cache/warp/1.3.3
Module __main__ 8267b0c load on device 'cuda:0' took 0.30 ms  (cached)
[0.7620355  1.1823659  1.0513412  ... 1.1199671  0.60416096 1.1344117 ]
running -----------------------------


And when I run this code of flows.it's ok:
```
# 检查torch cuda
import torch
import os


if torch.cuda.is_available():
    print("CUDA is available")
    # c查看CUDA版本
    print(f"CUDA version: {torch.version.cuda}")
    # 查看PyTorch版本
    print(f"PyTorch version: {torch.__version__}")
    # 查看GPU信息
    print(f"Current device: {torch.cuda.current_device()}")
    print(f"Current device name: {torch.cuda.get_device_name(torch.cuda.current_device())}")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("CUDA is not available")
    print("Using CPU")


import warp as wp
import numpy as np

num_points = 1024

@wp.kernel
def length(points: wp.array(dtype=wp.vec3),
           lengths: wp.array(dtype=float)):

    # thread index
    tid = wp.tid()
    
    # compute distance of each point from origin
    lengths[tid] = wp.length(points[tid])


# allocate an array of 3d points
points = wp.array(np.random.rand(num_points, 3), dtype=wp.vec3)
lengths = wp.zeros(num_points, dtype=float)

# launch kernel
wp.launch(kernel=length,
          dim=len(points),
          inputs=[points, lengths])

print(lengths)
print(f"running -----------------------------")
```

**Comment by fengjungui** [comment]
> Hi, I also encountered this problem before ([#22](https://github.com/rewarped/rewarped/issues/22)). What's your system information (CUDA version)? I solved it by upgrading CUDA version.

Hi,this is my information:
NVIDIA-SMI 535.216.03 驱动程序版本：535.216.03 CUDA 版本：12.2
CUDA 可用
CUDA 版本：12.6
PyTorch 版本：2.7.0+cu126
当前设备：0
当前设备名称：NVIDIA GeForce RTX 4090
GPU 数量：4
GPU 0：NVIDIA GeForce RTX 4090
GPU 1：NVIDIA GeForce RTX 4090
GPU 2：NVIDIA GeForce RTX 4090
GPU 3：NVIDIA GeForce RTX 4090
Warp 1.3.3 初始化：
CUDA Toolkit 12.5，驱动程序 12.2
设备：
“cpu”：“x86_64”
“cuda：0”：“NVIDIA GeForce RTX 4090”（24 GiB，sm_89，mempool启用）
“cuda：1”：“NVIDIA GeForce RTX 4090”（24 GiB，sm_89，已启用内存池）
“cuda：2”：“NVIDIA GeForce RTX 4090”（24 GiB，sm_89，已启用内存池）
“cuda：3”：“NVIDIA GeForce RTX 4090”（24 GiB，sm_89，已启用内存池）

**Comment by etaoxing** [comment]
It looks like there is a mismatch b/w your CUDA toolkit (12.5) and driver (12.2).

Did you [install CUDA using a runfile](https://docs.omniverse.nvidia.com/dev-guide/latest/linux-troubleshooting.html#q1-how-to-install-a-driver) or apt-get?

You could also try running `python -m warp.examples.core.example_graph_capture` or `python -m warp.tests` to doublecheck whether there is still some issue with your Warp install.
