### ISSUE TITLE
[QUESTION] Capturing wp.sim.collide()

### ISSUE THREAD

**Issue by DINHQuangDung1999** [rewarped/rewarped#28]
Hi authors, 

I am working on a project, in which I am reproducing the bounce experiments with different environment settings. I notice in your custom autograd script, [this block](https://github.com/rewarped/rewarped/blob/df92f42959cce47725bc42408b22497c6111cf99/rewarped/autograd.py#L107) captures the collision handling function `wp.sim.collide` into a graph. 
However, when I try to do the same, I get the following error. 

```
Warp 1.3.3 initialized:
   CUDA Toolkit 12.5, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA RTX 6000 Ada Generation" (47 GiB, sm_89, mempool enabled)
   Kernel cache:
     /home/qdinh/.cache/warp/1.3.3
Module warp.sim.collide 4936e06 load on device 'cuda:0' took 6.20 ms  (cached)
Module warp.sim.integrator_euler 3a49fc3 load on device 'cuda:0' took 1.25 ms  (cached)
Module warp.sim.integrator 036f39a load on device 'cuda:0' took 0.21 ms  (cached)
Module __main__ 4de069c load on device 'cuda:0' took 8.35 ms  (cached)
Warp CUDA error 1: invalid argument (in function memcpy_d2d, /builds/omniverse/warp/warp/native/warp.cu:652)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/qdinh/Desktop/working/.venv/lib/python3.10/site-packages/warp/examples/optim/example_bounce.py", line 258, in <module>
    example.check_grad()
  File "/home/qdinh/Desktop/working/.venv/lib/python3.10/site-packages/warp/examples/optim/example_bounce.py", line 212, in check_grad
    l_1 = self.forward().numpy()[0]
  File "/home/qdinh/Desktop/working/.venv/lib/python3.10/site-packages/warp/examples/optim/example_bounce.py", line 124, in forward
    wp.sim.collide(self.model, self.states[i])
  File "/home/qdinh/Desktop/working/.venv/lib/python3.10/site-packages/warp/sim/collide.py", line 1451, in collide
    model.soft_contact_body_pos = wp.clone(model.soft_contact_body_pos)
  File "/home/qdinh/Desktop/working/.venv/lib/python3.10/site-packages/warp/context.py", line 4279, in clone
    warp.copy(arr, src)
  File "/home/qdinh/Desktop/working/.venv/lib/python3.10/site-packages/warp/context.py", line 5258, in copy
    raise RuntimeError(f"Warp copy error: {runtime.get_error_string()}")
RuntimeError: Warp copy error: Warp CUDA error 1: invalid argument (in function memcpy_d2d, /builds/omniverse/warp/warp/native/warp.cu:652)
``` 

To reproduce this, you only need to add the function in right after [this line](https://github.com/NVIDIA/warp/blob/4acba4d3ad93082acb21bc2fa3c3180a533e7db3/warp/examples/optim/example_bounce.py#L123), i.e. 
```
            ...
            self.states[i].clear_forces()
            wp.sim.collide(self.model, self.states[i])
            self.integrator.simulate(self.model, self.states[i], self.states[i + 1], self.sim_dt)
            ...
```
and then run `python -m warp.examples.optim.example_bounce`. 

Would you mind explaining me how you make it work?

**Comment by DINHQuangDung1999** [comment]
I installed a fresh version of rewarped on my other laptop, but I ran into this problem, which seems to be originated from `wp.sim.collide`. 

```
Warp 1.3.3 initialized:
   CUDA Toolkit 12.5, Driver 12.2
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA RTX 4000 Ada Generation Laptop GPU" (12 GiB, sm_89, mempool enabled)
   Kernel cache:
     /home/dung-admin/.cache/warp/1.3.3
/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
Warp options: {'max_unroll': 16, 'enable_backward': True, 'fast_math': False, 'cuda_output': None, 'mode': 'release'}
/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Module warp.sim.collide 4936e06 load on device 'cuda:0' took 4.52 ms  (cached)
Module rewarped.warp.integrator_featherstone 4029f19 load on device 'cuda:0' took 0.84 ms  (cached)
Module warp.sim.articulation d301003 load on device 'cuda:0' took 0.68 ms  (cached)
grads: True, graph_capture: True, synchronize: False
Warp DeprecationWarning: Support for built-in functions called with non-Warp array types, such as lists, tuples, NumPy arrays, and others, will be dropped in the future. Use a Warp type such as `wp.vec`, `wp.mat`, `wp.quat`, or `wp.transform`.
/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/warp/torch.py:254: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  if t.grad is not None:
Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)
Warp CUDA error: Loading module failed
Module rewarped.warp.collide 4936e06 load on device 'cuda:0' took 0.77 ms  (error)
Traceback (most recent call last):
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/autograd.py", line 94, in forward
    sim_update(update_params, sim_params, states_bwd, control_bwd)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/warp_utils.py", line 43, in sim_update
    wp.sim.collide(model, state_0)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/warp/collide.py", line 1492, in collide
    wp.launch(
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/warp/context.py", line 4726, in launch
    module_exec = kernel.module.load(device)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/warp/context.py", line 1928, in load
    raise Exception(f"Failed to load CUDA module '{self.name}'")
Exception: Failed to load CUDA module 'rewarped.warp.collide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/envs/dflex/ant.py", line 212, in <module>
    run_env(Ant)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/environment.py", line 748, in run_env
    steps_per_second = demo.run()
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/warp_env.py", line 632, in run
    traj = self.run_episode(init_obs, policy)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/warp_env.py", line 671, in run_episode
    obs, reward, done, info = self.step(action)
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/warp_env.py", line 458, in step
    self.do_physics_step()
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/warp_env.py", line 414, in do_physics_step
    outputs = UpdateFunction.apply(
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/rewarped/autograd.py", line 96, in forward
    integrator.update_graph = wp.capture_end()
  File "/home/dung-admin/Desktop/working/.venv/lib/python3.10/site-packages/warp/context.py", line 5107, in capture_end
    raise RuntimeError(f"CUDA graph capture failed. {runtime.get_error_string()}")
RuntimeError: CUDA graph capture failed. Warp CUDA error 900: operation not permitted when stream is capturing (in function cuda_load_module, /builds/omniverse/warp/warp/native/warp.cu:2763)
```

**Comment by etaoxing** [comment]
For the first error, see [this diff](https://github.com/rewarped/rewarped/commit/4bdd4ed950ad1d6b392d1d57a33d28ccd1cd9338). Later versions of Warp fixed this bug, we hotfixed it with a custom `warp/collide.py`.

For the second error, you have the [wrong CUDA version installed](https://github.com/rewarped/rewarped/issues/24#issuecomment-2875287157).

**Comment by DINHQuangDung1999** [comment]
Thank you. I am currently using Warp 1.3.3. I might upgrade it later tho. The problem is solved where I commented on [this question](https://github.com/NVIDIA/warp/issues/467#issuecomment-2973650496).
